name: Build and Deploy Hugo Site to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Hugo
      run: |
        sudo apt-get update
        sudo apt-get install -y hugo

    - name: Build Hugo site
      run: hugo

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: your-s3-region
      run: |
        aws s3 sync public/ s3://madisonmansouri.com/ --delete
